#############
Find Products
Ignore,type,typeId,storeId	   
,BARCODE,085239152485,1375	   
,DPCI,071-08-1944,10	   
,TCIN,14525463,20	 
--------------------------------------------
#############
All Locations
Ignore,version
,1
,2
,3
--------------------------------------------
#####################
Beacon Composite Info
Ignore,storeId,locationId	   
,1375,900	   
,1375,201	   
Y,1375,202	   
,1375,203	   
,1375,204	   
,1375,205	   
,1375,206	   
,1375,207	   
,1375,208	   
,1375,209	   
,2766,900	   
,2766,201	   
,2766,202	   
,2766,203	   
,2766,204	   
,2766,205	   
,2766,206	   
,2766,207	   
,2766,208	   
,2766,209	   
,2300,900	   
,2300,201	   
,2300,202	   
,2300,203	   
,2300,204	   
,2300,205	   
,2300,206	   
,2300,207	   
,2300,208	   
,2300,209	   
,2786,900	   
,2786,201	   
,2786,202	   
,2786,203	   
,2786,204	   
,2786,205	   
,2786,206	   
,2786,207	   
,2786,208	   
,2786,209	   
,2766,900	   
,2766,201	   
,2766,202	   
,2766,203	   
,2766,204	   
,2766,205	   
,2766,206	   
,2766,207	   
,2766,208	   
,2766,209	   
,2799,900	   
,2799,201	   
,2799,202	   
,2799,203	   
,2799,204	   
,2799,205	   
,2799,206	   
,2799,207	   
,2799,208	   
,2799,209	 
--------------------------------------------
##########################
Extended Products by Group
Ignore,groupName,storeId	   
,top-deals,5	   
,top-deals,100	   
,top-deals,220	   
,top-deals,260	   
,top-deals,338	   
,top-deals,339	   
,top-deals,627	   
,top-deals,637	   
,top-deals,664	   
,top-deals,833	   
,top-deals,842	   
,top-deals,862	   
,top-deals,866	   
,top-deals,892	   
,top-deals,995	   
,top-deals,996	   
,top-deals,1024	   
,top-deals,1095	   
,top-deals,1118	   
,top-deals,1168	   
,top-deals,1213	   
,top-deals,1284	   
,top-deals,1356	   
,top-deals,1375	   
,top-deals,1385	   
,top-deals,1437	   
,top-deals,1849	   
,top-deals,2189	   
,top-deals,2223	   
,top-deals,2290	   
,top-deals,2300	   
,top-deals,2313	   
,top-deals,2378	   
,top-deals,2766	   
,top-deals,2768	   
,top-deals,2774	   
,top-deals,2775	   
,top-deals,2776	   
,top-deals,2786	   
,top-deals,2791	   
,top-deals,2799	   
,top-deals,2596	   
,top-deals,2810	   
,top-deals,2811	   
,top-deals,2847	   
,top-deals,2857	   
,top-deals,3200	   
,cartwheel:furniture,1375	   
,cartwheel:furniture,2300	   
,cartwheel:furniture,2786	   
,cartwheel:furniture,2766	   
,cartwheel:furniture,2799	   
,cartwheel:womens-apparel,1375	   
,cartwheel:womens-apparel,2300	   
,cartwheel:womens-apparel,2786	   
,cartwheel:womens-apparel,2766	   
,cartwheel:womens-apparel,2799	   
,cartwheel:patio-seasonal,1375	   
,cartwheel:patio-seasonal,2300	   
,cartwheel:patio-seasonal,2786	   
,cartwheel:patio-seasonal,2766	   
,cartwheel:patio-seasonal,2799	   
,cartwheel:baby,	1375	   
,cartwheel:baby,	2300	   
,cartwheel:baby,	2786	   
,cartwheel:baby,	2766	   
,cartwheel:baby,	2799	   
,cartwheel:mens-apparel,1375	   
,cartwheel:mens-apparel,2300	   
,cartwheel:mens-apparel,2786	   
,cartwheel:mens-apparel,2766	   
,cartwheel:mens-apparel,2799	   
,cartwheel:electronics,1375	   
,cartwheel:electronics,2300	   
,cartwheel:electronics,2786	   
,cartwheel:electronics,2766	   
,cartwheel:electronics,2799	   
,cartwheel:grocery,1375	   
,cartwheel:grocery,2300	   
,cartwheel:grocery,2786	   
,cartwheel:grocery,2766	   
,cartwheel:grocery,2799	   
,cartwheel:health-beauty,1375	   
,cartwheel:health-beauty,2300	   
,cartwheel:health-beauty,2786	   
,cartwheel:health-beauty,2766	   
,cartwheel:health-beauty,2799	   
,cartwheel:small-electronics,1375	   
,cartwheel:small-electronics,2300	   
,cartwheel:small-electronics,2786	   
,cartwheel:small-electronics,2766	   
,cartwheel:small-electronics,2799	   
,top-deals:furniture,1375	   
,top-deals:furniture,2300	   
,top-deals:furniture,2786	   
,top-deals:furniture,2766	   
,top-deals:furniture,2799	   
,top-deals:womens-apparel,1375	   
,top-deals:womens-apparel,2300	   
,top-deals:womens-apparel,2786	   
,top-deals:womens-apparel,2766	   
,top-deals:womens-apparel,2799	   
,top-deals:patio-seasonal,1375	   
,top-deals:patio-seasonal,2300	   
,top-deals:patio-seasonal,2786	   
,top-deals:patio-seasonal,2766	   
,top-deals:patio-seasonal,2799	   
,top-deals:baby,	1375	   
,top-deals:baby,	2300	   
,top-deals:baby,	2786	   
,top-deals:baby,	2766	   
,top-deals:baby,	2799	   
,top-deals:mens-apparel,1375	   
,top-deals:mens-apparel,2300	   
,top-deals:mens-apparel,2786	   
,top-deals:mens-apparel,2766	   
,top-deals:mens-apparel,2799	   
,top-deals:electronics,1375	   
,top-deals:electronics,2300	   
,top-deals:electronics,2786	   
,top-deals:electronics,2766	   
,top-deals:electronics,2799	   
,top-deals:grocery,1375	   
,top-deals:grocery,2300	   
,top-deals:grocery,2786	   
,top-deals:grocery,2766	   
,top-deals:grocery,2799	   
,top-deals:health-beauty,1375	   
,top-deals:health-beauty,2300	   
,top-deals:health-beauty,2786	   
,top-deals:health-beauty,2766	   
,top-deals:health-beauty,2799	   
,top-deals:small-electronics,1375	   
,top-deals:small-electronics,2300	   
,top-deals:small-electronics,2786	   
,top-deals:small-electronics,2766	   
,top-deals:small-electronics,2799	 
-------------------------------------------
#################
Trending - Basic
Ignore,name,store	   
,trending-top-added,1375	   
,trending-top-cart,1375	   
,trending-top-scans,1375	   
,trending-top-searched,1375	   
,trending-top-viewed,1375	   
,trending-top-added,5	   
,trending-top-cart,5	   
,trending-top-scans,5	   
,trending-top-searched,5	   
,trending-top-viewed,5	   
,trending-top-added,100	   
,trending-top-added,220	   
,trending-top-added,260	   
,trending-top-added,338	   
,trending-top-added,339	   
,trending-top-added,627	   
,trending-top-added,637	   
,trending-top-added,664	   
,trending-top-added,833	   
,trending-top-added,842	   
,trending-top-added,862	   
,trending-top-added,866	   
,trending-top-added,892	   
,trending-top-added,995	   
,trending-top-added,996	   
,trending-top-added,1024	   
,trending-top-added,1095	   
,trending-top-added,1118	   
,trending-top-added,1168	   
,trending-top-added,1213	   
,trending-top-added,1284	   
,trending-top-added,1356	   
,trending-top-added,1385	   
,trending-top-added,1437	   
,trending-top-added,1849	   
,trending-top-added,2189	   
,trending-top-added,2223	   
,trending-top-added,2290	   
,trending-top-added,2300	   
,trending-top-added,2313	   
,trending-top-added,2378	   
,trending-top-added,2596	   
,trending-top-added,2766	   
,trending-top-added,2768	   
,trending-top-added,2774	   
,trending-top-added,2775	   
,trending-top-added,2776	   
,trending-top-added,2786	   
,trending-top-added,2791	   
,trending-top-added,2799	   
,trending-top-added,2810	   
,trending-top-added,2811	   
,trending-top-added,2847	   
,trending-top-added,2857	   
,trending-top-added,3200	 
-------------------------------------------
#################
Trending - Legacy
Ignore,reportTypeId,store	   
,3,1375	   
,3,1375	   
,3,1375	   
,3,1375	   
,3,5	   
,3,5	   
,3,5	   
,3,5	   
,3,100	   
,3,220	   
,3,260	   
,3,338	   
,3,339	   
,3,627	   
,3,637	   
,3,664	   
,3,833	   
,3,842	   
,3,862	   
,3,866	   
,3,892	   
,3,995	   
,3,996	   
,3,1024	   
,3,1095	   
,3,1118	   
,3,1168	   
,3,1213	   
,3,1284	   
,3,1356	   
,3,1385	   
,3,1437	   
,3,1849	   
,3,2189	   
,3,2223	   
,3,2290	   
,3,2300	   
,3,2313	   
,3,2378	   
,3,2596	   
,3,2766	   
,3,2768	   
,3,2774	   
,3,2775	   
,3,2776	   
,3,2786	   
,3,2791	   
,3,2799	   
,3,2810	   
,3,2811	   
,3,2847	   
,3,2857	   
,3,3200	 
--------------------------------------------
####################
Trending - Composite
Ignore,store	   
,1375	   
,5	   
,100	   
,220	   
,260	   
,338	   
,339	   
,627	   
,637	   
,664	   
,833	   
,842	   
,862	   
,866	   
,892	   
,995	   
,996	   
,1024	   
,1095	   
,1118	   
,1168	   
,1213	   
,1284	   
,1356	   
,1385	   
,1437	   
,1849	   
,2189	   
,2223	   
,2290	   
,2300	   
,2313	   
,2378	   
,2596	   
,2766	   
,2768	   
,2774	   
,2775	   
,2776	   
,2786	   
,2791	   
,2799	   
,2810	   
,2811	   
,2847	   
,2857	   
,3200	 
--------------------------------------------
##################
Showcase Products 
Ignore,name,store	   
,top-deals,1375	   
,awesomeshop,1375	   
,trending-top-added,1375	   
,trending-top-cart,1375	   
,trending-top-scans,1375	   
,trending-top-searched,1375	   
,trending-top-viewed,1375	   
,top-deals,5	   
,awesomeshop,5	   
,trending-top-added,5	   
,trending-top-cart,5	   
,trending-top-scans,5	   
,trending-top-searched,5	   
,trending-top-viewed,	5	 
--------------------------------------------
##################
RedSky Generic 2 Specific
Ignore,location,	store,search-term	   
,inside,1375,milk	   
,outside,1375,milk	   
,inside,1375,engine oil	   
,outside,1375,engine oil	   
,inside,1375,plant	   
,outside,1375,plant	   
,inside,1375,eggs	   
,outside,1375,eggs	   
,inside,1375,shirt	   
,outside,1375,shirt	   
,inside,1375,bananas	   
,outside,1375,bananas	   
,inside,1375,balloons	   
,outside,1375,balloons	   
,inside,1385,milk	   
,outside,1385,milk	   
,inside,1385,engine oil	   
,outside,1385,engine oil	   
,inside,1385,plant	   
,outside,1385,plant	   
,inside,1385,eggs	   
,outside,1385,eggs	   
,inside,1385,shirt	   
,outside,1385,shirt	   
,inside,1385,bananas	   
,outside,1385,bananas	   
,inside,1385,balloons	   
,outside,1385,balloons	 
--------------------------------------------
##################
Location Details 
Ignore,storeId	   
,1375 
,5	   
,100	   
,220	   
,260	   
,338	   
,339	   
,627	   
,637	   
,664	   
,833	   
,842	   
,862	   
,866	   
,892	   
,995	   
,996	   
,1024	   
,1095	   
,1118	   
,1168	   
,1213	   
,1284	   
,1356	   
,1385	   
,1437	   
,1849	   
,2189	   
,2223	   
,2290	   
,2300	   
,2313	   
,2378	   
,2596	   
,2766	   
,2768	   
,2774	   
,2775	   
,2776	   
,2786	   
,2791	   
,2799	   
,2810	   
,2811	   
,2847	   
,2857	   
,3200	 
-------------------------------------------
